### ISSUE TITLE
The specified blob does not exist

### ISSUE THREAD

**Issue by mloskot** [coapp-packages/zlib#1]
While trying to download vc10 binaries of zlib package from the feed website at http://coapp.org/pages/packages.html
I'm getting the URL of http://downloads.coapp.org/repository/zlib%5Bvc10%5D-1.2.5.35-x86.msi loaded but no binary is downloaded. Instead, browser displays the following error:

```
BlobNotFound
The specified blob does not exist.
RequestId:87415552-12a3-4035-a5ec-c65b41fa5076
Time:2012-03-23T00:49:32.8652769Z
```

**Comment by ferzkopp** [comment]
Can you try the CoApp mailing list ... I am not too familiar with this 
error message.
--Andreas

**Comment by mloskot** [comment]
Done here https://lists.launchpad.net/coapp-developers/msg01282.html

**Comment by riverar** [comment]
Can we close this issue?
