### ISSUE TITLE
library names are confusing

### ISSUE THREAD

**Issue by madewokherd** [coapp-packages/zlib#3]
In my library folder, I have zlib, zlib1, zlibwapi, and zlibstat. Two of those are stdcall and two are cdecl. Two are static and two are dynamic. Which ones are which? I don't know.

Someone was confused by the fact that zlibstat was stdcall.

I think static libs need to have a clear relation to the dynamic ones, such as appending -static to the name.

**Comment by OlafvdSpek** [comment]
IMO lib output names should (by default) be automatically generated by the coapp framework.
Same for the output configurations, as some are missing. Static libs can be linked with either the dynamic runtime or the static runtime. I use the static runtime, but others might need the dynamic one, so both variants should be generated.

**Comment by OlafvdSpek** [comment]
Any progress? ;)

**Comment by madewokherd** [comment]
CoApp has been abandoned in favor of nuget packages, which do not require knowledge of .lib filenames.

**Comment by tfwio** [comment]
NB: http://www.zlib.net/DLL_FAQ.txt
