### ISSUE TITLE
NuGet support for MSVC 2013

### ISSUE THREAD

**Issue by ghost** [coapp-packages/zlib#7]
The package does install and compile, but does neither link nor copy the Dlls. As fas as I understand, the corresponding targets are simply missing.

I plan to use the package in a pratical exercise for a lecture I will be giving at my university. So I would really appreciate if you could fix that.

**Comment by aggieben** [comment]
I also am unable to build using this nuget package:

> Error 17  error LNK2019: unresolved external symbol gzdopen referenced in function "public: virtual int __cdecl comp_io_buf::open_file(char const *,bool,int)" (?open_file@comp_io_buf@@UEAAHPEBD_NH@Z)   C:\Users\Benjamin\src\vowpal_wabbit\vowpalwabbit\vw_static.lib(parser.obj)  libvw
> Error 18  error LNK2019: unresolved external symbol gzread referenced in function "public: virtual unsigned __int64 __cdecl comp_io_buf::read_file(int,void *,unsigned __int64)" (?read_file@comp_io_buf@@UEAA_KHPEAX_K@Z)    C:\Users\Benjamin\src\vowpal_wabbit\vowpalwabbit\vw_static.lib(parser.obj)  libvw
> Error 19  error LNK2019: unresolved external symbol gzwrite referenced in function "public: virtual unsigned __int64 __cdecl comp_io_buf::write_file(int,void const *,unsigned __int64)" (?write_file@comp_io_buf@@UEAA_KHPEBX_K@Z)   C:\Users\Benjamin\src\vowpal_wabbit\vowpalwabbit\vw_static.lib(parser.obj)  libvw
> Error 20  error LNK2019: unresolved external symbol gzclose referenced in function "public: virtual bool __cdecl comp_io_buf::close_file(void)" (?close_file@comp_io_buf@@UEAA_NXZ)   C:\Users\Benjamin\src\vowpal_wabbit\vowpalwabbit\vw_static.lib(parser.obj)  libvw
> Error 21  error LNK2019: unresolved external symbol gzopen referenced in function "public: virtual int __cdecl comp_io_buf::open_file(char const *,bool,int)" (?open_file@comp_io_buf@@UEAAHPEBD_NH@Z)    C:\Users\Benjamin\src\vowpal_wabbit\vowpalwabbit\vw_static.lib(parser.obj)  libvw
> Error 22  error LNK2019: unresolved external symbol gzseek referenced in function "public: virtual void __cdecl comp_io_buf::reset_file(int)" (?reset_file@comp_io_buf@@UEAAXH@Z) C:\Users\Benjamin\src\vowpal_wabbit\vowpalwabbit\vw_static.lib(parser.obj)  libvw
> Error 23  error LNK2001: unresolved external symbol "struct Searn::searn_task MulticlassTask::task" (?task@MulticlassTask@@3Usearn_task@Searn@@A) C:\Users\Benjamin\src\vowpal_wabbit\vowpalwabbit\vw_static.lib(searn.obj)   libvw
> Error 24  error LNK1120: 7 unresolved externals   C:\Users\Benjamin\src\vowpal_wabbit\vowpalwabbit\dll\x64\Debug\libvw.dll    libvw

I tried re-installing the package to make sure files were copied correctly and that project files were updated with the import expressions, but it didn't change anything.  Is there something else that must be done to make the package work?  I'd rather not have to set paths and such; that kind of defeats the purpose of nuget.

**Comment by ghost** [comment]
Seams msvc v120 targets have been added. Thanks!
